import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import {
  REPORT_PERIOD_LABEL,
  REPORT_VERSION,
  POST_AWARD_REPORT_PERIOD_LABEL,
  POST_AWARD_REPORT_VERSION,
} from "../config/snapshot";

export interface ExportRoute {
  path: string;
  label: string;
}

/** Currently implemented pages only. Placeholder routes (Project Register)
 *  intentionally excluded — capturing an empty "not yet implemented" page
 *  in the PDF would mislead the reader. Add each new page here once it's
 *  built. */
export const EXPORT_ROUTES: ExportRoute[] = [
  { path: "/executive-overview", label: "Executive Overview" },
  { path: "/geographic-analysis", label: "Geographic Analysis" },
  { path: "/award-analysis", label: "Awards Performance" },
  { path: "/pipeline-analysis", label: "Pipeline Analysis" },
  { path: "/assignee-performance", label: "Team Performance" },
  { path: "/agreements-analysis", label: "Agreements Register" },
];

/** Post-Award report pages, captured in the same way as EXPORT_ROUTES. Kept
 * as a separate list (rather than merging) because the two reports are
 * independent uploads/tabs — a single PDF never mixes Pre- and Post-Award
 * pages. */
export const POST_AWARD_EXPORT_ROUTES: ExportRoute[] = [
  { path: "/post-award/overview", label: "Portfolio Overview" },
  { path: "/post-award/claims-vo", label: "Claims & Variation Orders" },
  { path: "/post-award/invoicing", label: "Invoicing & Cashflow" },
  { path: "/post-award/closeout", label: "TOC/DLC Closeout" },
  { path: "/post-award/subcontractors", label: "Subcontractor Management" },
  { path: "/post-award/agreements", label: "Special Agreements" },
  { path: "/post-award/correspondence", label: "Correspondence & Register" },
];

const CAPTURE_SELECTOR = ".report-canvas";
const RENDER_SETTLE_MS = 1400;

async function waitForRender(): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, RENDER_SETTLE_MS));
  if (document.fonts && document.fonts.ready) {
    await document.fonts.ready;
  }
  await new Promise<void>((resolve) => {
    requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
  });
}

/** Modify the CLONED DOM only (live DOM stays untouched, no visible reflow
 *  during export). Two classes of edits:
 *    1. Unlock every scrollable region so all rows render in full — fixes
 *       the "AssigneeTable showed only 4 of 10 rows" and
 *       "CountryComparisonTable missing UAE/Benin" defects.
 *    2. Replace every native <select> with a <span> showing the selected
 *       option's text — html2canvas cannot capture the browser-native
 *       selected-option rendering, which was producing empty ".." filter
 *       labels in the exported PDF. */
function prepareCloneForCapture(clonedDoc: Document): void {
  const canvasEl = clonedDoc.querySelector<HTMLElement>(CAPTURE_SELECTOR);
  if (canvasEl) {
    canvasEl.style.height = "auto";
    canvasEl.style.minHeight = "720px";
    canvasEl.style.overflow = "visible";
  }

  // G-1 fix: Promote the print-only report chrome (PrintReportHeader,
  // PrintReportFooter) to visible in the capture. Otherwise every PDF
  // generated by the button loses the confidential footer, snapshot date,
  // filter record, and page counter — turning the primary distribution
  // artifact into an unmarked document. `.print-only` is display:none on
  // screen; we override it in the clone only. Also hide `.no-print`
  // elements (interactive filter dropdowns above the print header) so
  // the print header owns the top-of-page real estate.
  clonedDoc.querySelectorAll<HTMLElement>(".print-only").forEach((el) => {
    el.style.display = "flex";
  });
  clonedDoc.querySelectorAll<HTMLElement>(".no-print").forEach((el) => {
    el.style.display = "none";
  });

  const scrollSel = ".overflow-hidden, .overflow-y-auto, .overflow-auto, .overflow-x-auto";
  clonedDoc.querySelectorAll<HTMLElement>(scrollSel).forEach((el) => {
    el.style.overflow = "visible";
    el.style.maxHeight = "none";
  });

  clonedDoc.querySelectorAll<HTMLElement>('[style*="overflow"]').forEach((el) => {
    const s = el.style;
    if (
      s.overflowY === "auto" ||
      s.overflow === "auto" ||
      s.overflowX === "auto" ||
      s.overflow === "hidden" ||
      s.overflowY === "hidden"
    ) {
      el.style.overflow = "visible";
      el.style.maxHeight = "none";
    }
  });

  clonedDoc.querySelectorAll<HTMLElement>(".pf-row").forEach((el) => {
    el.style.height = "auto";
    el.style.minHeight = "0";
  });

  // KPI strip is deliberately NOT tagged .pf-row (it kept its 106 px
  // lock for the browser-print pass). In the PDF export we do want it
  // to grow so the KPI card content (icon + label + 25 px value +
  // subtitle + trend + footnote — ~130 px total) doesn't get clipped.
  // Force min-height 140 px so the largest KPI card (with multi-line
  // currency breakdown value) fits comfortably. Range 100-110 catches
  // the strip inline height without touching smaller pixel-locked
  // elements (icon badges, progress bars, milestone bars). */
  clonedDoc.querySelectorAll<HTMLElement>("div").forEach((el) => {
    if (!el.style || !el.style.height) return;
    const px = parseFloat(el.style.height);
    if (Number.isFinite(px) && px >= 100 && px <= 135) {
      el.style.height = "auto";
      el.style.minHeight = "150px";
    }
  });

  // Also promote KPICards (className contains "bg-card overflow-hidden"):
  // force overflow visible + min-height so the value + subtitle + trend
  // never get clipped by the card's own overflow rule. */
  clonedDoc.querySelectorAll<HTMLElement>(".bg-card").forEach((el) => {
    el.style.overflow = "visible";
    const parent = el.parentElement;
    if (parent && parent.className && parent.className.includes("flex") && parent.className.includes("gap-2")) {
      const parentH = parent.style.height ? parseFloat(parent.style.height) : NaN;
      if (Number.isFinite(parentH) && parentH >= 100 && parentH <= 135) {
        el.style.minHeight = "150px";
      }
    }
  });

  // KPI cards themselves keep their overflow-hidden (already released
  // by the scrollSel pass above), but their internal `padding: "10px 12px"`
  // + `gap: 3` are OK on paper — no further tweaks needed. */

  clonedDoc.querySelectorAll<HTMLSelectElement>("select").forEach((select) => {
    const opt = select.options[select.selectedIndex];
    const label = opt?.text?.trim() || "All";
    const span = clonedDoc.createElement("span");
    span.textContent = label;
    const computed = window.getComputedStyle(select);
    span.style.fontSize = computed.fontSize;
    span.style.fontWeight = computed.fontWeight;
    span.style.color = computed.color;
    span.style.padding = "5px 20px 5px 8px";
    span.style.border = computed.border;
    span.style.borderRadius = computed.borderRadius;
    span.style.background = "white";
    span.style.display = "inline-block";
    span.style.minWidth = computed.width;
    span.style.lineHeight = "1.2";
    span.style.fontFamily = computed.fontFamily;
    select.parentNode?.replaceChild(span, select);
  });
}

async function exportRoutesAsPdf(
  routes: ExportRoute[],
  navigate: (path: string) => void,
  originalPath: string,
  fileName: string,
): Promise<void> {
  const pdf = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
    compress: true,
  });
  const pageWidthMm = pdf.internal.pageSize.getWidth();
  const pageHeightMm = pdf.internal.pageSize.getHeight();

  for (let i = 0; i < routes.length; i++) {
    const route = routes[i];
    navigate(route.path);
    await waitForRender();

    const element = document.querySelector<HTMLElement>(CAPTURE_SELECTOR);
    if (!element) continue;

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
      logging: false,
      onclone: prepareCloneForCapture,
    });

    const imgData = canvas.toDataURL("image/png");
    const imgAspect = canvas.width / canvas.height;
    const pageAspect = pageWidthMm / pageHeightMm;
    let w: number;
    let h: number;
    if (imgAspect > pageAspect) {
      w = pageWidthMm;
      h = pageWidthMm / imgAspect;
    } else {
      h = pageHeightMm;
      w = pageHeightMm * imgAspect;
    }
    const x = (pageWidthMm - w) / 2;
    const y = (pageHeightMm - h) / 2;
    if (i > 0) pdf.addPage();
    pdf.addImage(imgData, "PNG", x, y, w, h);
  }

  navigate(originalPath);
  pdf.save(fileName);
}

export async function exportReportAsPdf(
  navigate: (path: string) => void,
  originalPath: string,
): Promise<void> {
  const today = new Date().toISOString().slice(0, 10);
  const period = REPORT_PERIOD_LABEL.replace(/\s+/g, "_");
  await exportRoutesAsPdf(EXPORT_ROUTES, navigate, originalPath, `ROWAD_Pre-Award_${period}_v${REPORT_VERSION}_${today}.pdf`);
}

export async function exportPostAwardReportAsPdf(
  navigate: (path: string) => void,
  originalPath: string,
): Promise<void> {
  const today = new Date().toISOString().slice(0, 10);
  const period = POST_AWARD_REPORT_PERIOD_LABEL.replace(/\s+/g, "_");
  await exportRoutesAsPdf(
    POST_AWARD_EXPORT_ROUTES,
    navigate,
    originalPath,
    `ROWAD_Post-Award_${period}_v${POST_AWARD_REPORT_VERSION}_${today}.pdf`,
  );
}
